### ISSUE TITLE
Protocol-relative resources not included

### ISSUE THREAD

**Issue by romgrk** [remy/inliner#123]
Doesn't work:
```html
<script src="//foo.com/bar.js"></script>
```

Works:
```html
<script src="https://foo.com/bar.js"></script>
```

**Comment by remy** [comment]
How do you replicate this bug when using the inliner? Is it via a file, inline HTML or pointing to a url?

**Comment by romgrk** [comment]
Via a file

**Comment by seanho00** [comment]
For instance, I'm using [a Google early-access webfont](https://fonts.googleapis.com/earlyaccess/cwtexkai.css) whose CSS uses protocol-relative URLs to grab the various WOFF/TTF/etc font files.

The webfont CSS is `@import`ed in a CSS that is `<link rel=stylesheet>` in an HTML file that is sent to inliner via command-line, e.g., `inliner index.html`.

Inliner finds the webfont CSS fine, but doesn't load the WOFF/TTF files, showing errors like
```
warning: no such file: cwTeXKai-zhonly.woff
```

**Comment by vancetran** [comment]
For font files, I found a workaround and was able to keep relative links. It seems that inliner doesn't like spaces in font files when referenced relatively.

```css
@font-face {
  font-family: 'Gotham';
  src: url('/fonts/Gotham Book.eot');
  src: url('/fonts/Gotham Book.woff') format('woff'), url('../fonts/Gotham Book.ttf') format('truetype');
  font-weight: 400;
  font-style: normal;
}
```

Got these errors with inliner:

```sh
49% remaining: images(14)
52% remaining: images(13)
‣ 404 on Gotham%20Book.eot


52% remaining: images(13)
56% remaining: images(12)
‣ 404 on Gotham%20Book.ttf


56% remaining: images(12)
60% remaining: images(11)
‣ 404 on Gotham%20Book.woff
```
No 404 errors from this:
```css
@font-face {
  font-family: 'Gotham';
  src: url('/fonts/GothamBook.eot');
  src: url('/fonts/GothamBook.woff') format('woff'), url('../fonts/GothamBook.ttf') format('truetype');
  font-weight: 400;
  font-style: normal;
}
```
