### ISSUE TITLE
Relative @font-face URLs not loading font files that include spaces

### ISSUE THREAD

**Issue by vancetran** [remy/inliner#166]
It seems that Inliner gives 404 errors when @font-face references font files relatively. The first workaround I used was absolute URLs, ex: `https://localhost:3000/font/Gotham Bold.ttf`

I found another workaround and was able to maintain relative links. It seems that inliner doesn't like spaces in font filenames when referenced relatively.

```css
@font-face {
  font-family: 'Gotham';
  src: url('/fonts/Gotham Book.eot');
  src: url('/fonts/Gotham Book.woff') format('woff'), url('../fonts/Gotham Book.ttf') format('truetype');
  font-weight: 400;
  font-style: normal;
}
```

Got these errors with inliner:

```sh
49% remaining: images(14)
52% remaining: images(13)
‣ 404 on Gotham%20Book.eot


52% remaining: images(13)
56% remaining: images(12)
‣ 404 on Gotham%20Book.ttf


56% remaining: images(12)
60% remaining: images(11)
‣ 404 on Gotham%20Book.woff
```
No 404 errors from this:
```css
@font-face {
  font-family: 'Gotham';
  src: url('/fonts/GothamBook.eot');
  src: url('/fonts/GothamBook.woff') format('woff'), url('../fonts/GothamBook.ttf') format('truetype');
  font-weight: 400;
  font-style: normal;
}
```

**Comment by MrSco** [comment]
> It seems that Inliner gives 404 errors when @font-face references font files relatively. The first workaround I used was absolute URLs, ex: `https://localhost:3000/font/Gotham Bold.ttf`
> 
> I found another workaround and was able to maintain relative links. It seems that inliner doesn't like spaces in font filenames when referenced relatively.
> 

what was your workaround for relative @font-face links?

**Comment by aldanor** [comment]
Hit this as well with 'League Gothic' font from reveal.js (solarized theme). Here inliner complains about "no such file" for all of these files:

```css
@font-face {
    font-family: 'League Gothic';
    src: url('league-gothic.eot');
    src: url('league-gothic.eot?#iefix') format('embedded-opentype'),
         url('league-gothic.woff') format('woff'),
         url('league-gothic.ttf') format('truetype');

    font-weight: normal;
    font-style: normal;
}
```

Not sure if it matters, but this is imported from another css which is imported from another css.
